<?php
/**
 * Behavior Builder abstract class
 */
class SBehaviorBuilder{
	
	/**
	 * Create an autogenerated Model
	 * 
	 * @param string
	 * @param string
	 * @param string
	 * @param string
	 */
	public static function createModel($modelFile,$modelName,$content,$contentClassAnnotations=''){
		file_put_contents(dirname($modelFile->srcFile()->getPath()).'/'.$modelName.'.php',
			'<?php /* CLASS GENERATED BY '.get_called_class().' FOR MODEL '.$modelFile->_className.' | PLEASE DO NOT EDIT */ '
			."\n".(empty($contentClassAnnotations)?'':'/** '.$contentClassAnnotations.' */')
			."\n".'class '.$modelName.' extends SSqlModel{'
				."\n".$content
			."\n".'}');
	}
}
