'use strict';for(var html5elements="address article aside audio canvas command datalist details dialog figure figcaption footer header hgroup keygen mark meter menu nav progress ruby section time video".split(" "),i=0;i<html5elements.length;i++)document.createElement(html5elements[i]);
(function(){function w(){}function E(a){try{return Object.defineProperty(a,"sentinel",{}),"sentinel"in a}catch(b){}}function F(a){a=+a;a!==a?a=0:0!==a&&(a!==1/0&&a!==-(1/0))&&(a=(0<a||-1)*Math.floor(Math.abs(a)));return a}function x(a){var b=typeof a;return null===a||"undefined"===b||"boolean"===b||"number"===b||"string"===b}Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError("Function.prototype.bind called on incompatible "+b);var d=
u.call(arguments,1),c=function(){if(this instanceof c){var e=b.apply(this,d.concat(u.call(arguments)));return Object(e)===e?e:this}return b.apply(a,d.concat(u.call(arguments)))};b.prototype&&(w.prototype=b.prototype,c.prototype=new w,w.prototype=null);return c});var k=Function.prototype.call,n=Object.prototype,u=Array.prototype.slice,h=k.bind(n.toString),p=k.bind(n.hasOwnProperty),G,H,y,z,v;if(v=p(n,"__defineGetter__"))G=k.bind(n.__defineGetter__),H=k.bind(n.__defineSetter__),y=k.bind(n.__lookupGetter__),
z=k.bind(n.__lookupSetter__);if(2!=[1,2].splice(0).length){var L=Array.prototype.splice;Array.prototype.splice=function(a,b){return arguments.length?L.apply(this,[void 0===a?0:a,void 0===b?this.length-a:b].concat(u.call(arguments,2))):[]}}if(1!=[].unshift(0)){var M=Array.prototype.unshift;Array.prototype.unshift=function(){M.apply(this,arguments);return this.length}}Array.isArray||(Array.isArray=function(a){return"[object Array]"==h(a)});var k=Object("a"),r="a"!=k[0]||!(0 in k);Array.prototype.forEach||
(Array.prototype.forEach=function(a,b){var d=s(this),c=r&&"[object String]"==h(this)?this.split(""):d,e=-1,f=c.length>>>0;if("[object Function]"!=h(a))throw new TypeError;for(;++e<f;)e in c&&a.call(b,c[e],e,d)});Array.prototype.map||(Array.prototype.map=function(a,b){var d=s(this),c=r&&"[object String]"==h(this)?this.split(""):d,e=c.length>>>0,f=Array(e);if("[object Function]"!=h(a))throw new TypeError(a+" is not a function");for(var g=0;g<e;g++)g in c&&(f[g]=a.call(b,c[g],g,d));return f});Array.prototype.filter||
(Array.prototype.filter=function(a,b){var d=s(this),c=r&&"[object String]"==h(this)?this.split(""):d,e=c.length>>>0,f=[],g;if("[object Function]"!=h(a))throw new TypeError(a+" is not a function");for(var j=0;j<e;j++)j in c&&(g=c[j],a.call(b,g,j,d)&&f.push(g));return f});Array.prototype.every||(Array.prototype.every=function(a,b){var d=s(this),c=r&&"[object String]"==h(this)?this.split(""):d,e=c.length>>>0;if("[object Function]"!=h(a))throw new TypeError(a+" is not a function");for(var f=0;f<e;f++)if(f in
c&&!a.call(b,c[f],f,d))return!1;return!0});Array.prototype.some||(Array.prototype.some=function(a,b){var d=s(this),c=r&&"[object String]"==h(this)?this.split(""):d,e=c.length>>>0;if("[object Function]"!=h(a))throw new TypeError(a+" is not a function");for(var f=0;f<e;f++)if(f in c&&a.call(b,c[f],f,d))return!0;return!1});Array.prototype.reduce||(Array.prototype.reduce=function(a){var b=s(this),d=r&&"[object String]"==h(this)?this.split(""):b,c=d.length>>>0;if("[object Function]"!=h(a))throw new TypeError(a+
" is not a function");if(!c&&1==arguments.length)throw new TypeError("reduce of empty array with no initial value");var e=0,f;if(2<=arguments.length)f=arguments[1];else{do{if(e in d){f=d[e++];break}if(++e>=c)throw new TypeError("reduce of empty array with no initial value");}while(1)}for(;e<c;e++)e in d&&(f=a.call(void 0,f,d[e],e,b));return f});Array.prototype.reduceRight||(Array.prototype.reduceRight=function(a){var b=s(this),d=r&&"[object String]"==h(this)?this.split(""):b,c=d.length>>>0;if("[object Function]"!=
h(a))throw new TypeError(a+" is not a function");if(!c&&1==arguments.length)throw new TypeError("reduceRight of empty array with no initial value");var e,c=c-1;if(2<=arguments.length)e=arguments[1];else{do{if(c in d){e=d[c--];break}if(0>--c)throw new TypeError("reduceRight of empty array with no initial value");}while(1)}do c in this&&(e=a.call(void 0,e,d[c],c,b));while(c--);return e});if(!Array.prototype.indexOf||-1!=[0,1].indexOf(1,2))Array.prototype.indexOf=function(a){var b=r&&"[object String]"==
h(this)?this.split(""):s(this),d=b.length>>>0;if(!d)return-1;var c=0;1<arguments.length&&(c=F(arguments[1]));for(c=0<=c?c:Math.max(0,d+c);c<d;c++)if(c in b&&b[c]===a)return c;return-1};if(!Array.prototype.lastIndexOf||-1!=[0,1].lastIndexOf(0,-3))Array.prototype.lastIndexOf=function(a){var b=r&&"[object String]"==h(this)?this.split(""):s(this),d=b.length>>>0;if(!d)return-1;var c=d-1;1<arguments.length&&(c=Math.min(c,F(arguments[1])));for(c=0<=c?c:d-Math.abs(c);0<=c;c--)if(c in b&&a===b[c])return c;
return-1};if(!Object.keys){var I=!0,J="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),N=J.length,l;for(l in{toString:null})I=!1;Object.keys=function(a){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.keys called on a non-object");var b=[],d;for(d in a)p(a,d)&&b.push(d);if(I)for(d=0;d<N;d++){var c=J[d];p(a,c)&&b.push(c)}return b}}Object.getPrototypeOf||(Object.getPrototypeOf=function(a){return a.__proto__||
(a.constructor?a.constructor.prototype:n)});Object.getOwnPropertyDescriptor||(Object.getOwnPropertyDescriptor=function(a,b){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object: "+a);if(p(a,b)){var d={enumerable:!0,configurable:!0};if(v){var c=a.__proto__;a.__proto__=n;var e=y(a,b),f=z(a,b);a.__proto__=c;if(e||f)return e&&(d.get=e),f&&(d.set=f),d}d.value=a[b];return d}});Object.getOwnPropertyNames||(Object.getOwnPropertyNames=
function(a){return Object.keys(a)});if(!Object.create){var A;if(null===Object.prototype.__proto__||"undefined"==typeof document)A=function(){return{__proto__:null}};else{var K=function(){};l=document.createElement("iframe");k=document.body||document.documentElement;l.style.display="none";k.appendChild(l);l.src="javascript:";var t=l.contentWindow.Object.prototype;k.removeChild(l);l=null;delete t.constructor;delete t.hasOwnProperty;delete t.propertyIsEnumerable;delete t.isPrototypeOf;delete t.toLocaleString;
delete t.toString;delete t.valueOf;t.__proto__=null;K.prototype=t;A=function(){return new K}}Object.create=function(a,b){function d(){}var c;if(null===a)c=A();else{if("object"!==typeof a&&"function"!==typeof a)throw new TypeError("Object prototype may only be an Object or null");d.prototype=a;c=new d;c.__proto__=a}void 0!==b&&Object.defineProperties(c,b);return c}}if(Object.defineProperty&&(l=E({}),k="undefined"==typeof document||E(document.createElement("div")),!l||!k))var B=Object.defineProperty,
C=Object.defineProperties;if(!Object.defineProperty||B)Object.defineProperty=function(a,b,d){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.defineProperty called on non-object: "+a);if("object"!=typeof d&&"function"!=typeof d||null===d)throw new TypeError("Property description must be an object: "+d);if(B)try{return B.call(Object,a,b,d)}catch(c){}if(p(d,"value"))if(v&&(y(a,b)||z(a,b))){var e=a.__proto__;a.__proto__=n;delete a[b];a[b]=d.value;a.__proto__=e}else a[b]=
d.value;else{if(!v)throw new TypeError("getters & setters can not be defined on this javascript engine");p(d,"get")&&G(a,b,d.get);p(d,"set")&&H(a,b,d.set)}return a};if(!Object.defineProperties||C)Object.defineProperties=function(a,b){if(C)try{return C.call(Object,a,b)}catch(d){}for(var c in b)p(b,c)&&"__proto__"!=c&&Object.defineProperty(a,c,b[c]);return a};Object.seal||(Object.seal=function(a){return a});Object.freeze||(Object.freeze=function(a){return a});try{Object.freeze(function(){})}catch(V){var O=
Object.freeze;Object.freeze=function(a){return"function"==typeof a?a:O(a)}}Object.preventExtensions||(Object.preventExtensions=function(a){return a});Object.isSealed||(Object.isSealed=function(){return!1});Object.isFrozen||(Object.isFrozen=function(){return!1});Object.isExtensible||(Object.isExtensible=function(a){if(Object(a)!==a)throw new TypeError;for(var b="";p(a,b);)b+="?";a[b]=!0;var d=p(a,b);delete a[b];return d});if(!Date.prototype.toISOString||-1===(new Date(-621987552E5)).toISOString().indexOf("-000001"))Date.prototype.toISOString=
function(){var a,b,d,c;if(!isFinite(this))throw new RangeError("Date.prototype.toISOString called on non-finite value.");c=this.getUTCFullYear();a=this.getUTCMonth();c+=Math.floor(a/12);a=[(a%12+12)%12+1,this.getUTCDate(),this.getUTCHours(),this.getUTCMinutes(),this.getUTCSeconds()];c=(0>c?"-":9999<c?"+":"")+("00000"+Math.abs(c)).slice(0<=c&&9999>=c?-4:-6);for(b=a.length;b--;)d=a[b],10>d&&(a[b]="0"+d);return c+"-"+a.slice(0,2).join("-")+"T"+a.slice(2).join(":")+"."+("000"+this.getUTCMilliseconds()).slice(-3)+
"Z"};l=!1;try{l=Date.prototype.toJSON&&null===(new Date(NaN)).toJSON()&&-1!==(new Date(-621987552E5)).toJSON().indexOf("-000001")&&Date.prototype.toJSON.call({toISOString:function(){return!0}})}catch(W){}l||(Date.prototype.toJSON=function(){var a=Object(this),b;a:if(x(a))b=a;else{b=a.valueOf;if("function"===typeof b&&(b=b.call(a),x(b)))break a;b=a.toString;if("function"===typeof b&&(b=b.call(a),x(b)))break a;throw new TypeError;}if("number"===typeof b&&!isFinite(b))return null;b=a.toISOString;if("function"!=
typeof b)throw new TypeError("toISOString property is not callable");return b.call(a)});var g=Date,q=function(a,b,d,c,e,f,h){var j=arguments.length;return this instanceof g?(j=1==j&&String(a)===a?new g(q.parse(a)):7<=j?new g(a,b,d,c,e,f,h):6<=j?new g(a,b,d,c,e,f):5<=j?new g(a,b,d,c,e):4<=j?new g(a,b,d,c):3<=j?new g(a,b,d):2<=j?new g(a,b):1<=j?new g(a):new g,j.constructor=q,j):g.apply(this,arguments)},D=function(a,b){var d=1<b?1:0;return P[b]+Math.floor((a-1969+d)/4)-Math.floor((a-1901+d)/100)+Math.floor((a-
1601+d)/400)+365*(a-1970)},Q=RegExp("^(\\d{4}|[+-]\\d{6})(?:-(\\d{2})(?:-(\\d{2})(?:T(\\d{2}):(\\d{2})(?::(\\d{2})(?:\\.(\\d{3}))?)?(Z|(?:([-+])(\\d{2}):(\\d{2})))?)?)?)?$"),P=[0,31,59,90,120,151,181,212,243,273,304,334,365],m;for(m in g)q[m]=g[m];q.now=g.now;q.UTC=g.UTC;q.prototype=g.prototype;q.prototype.constructor=q;q.parse=function(a){var b=Q.exec(a);if(b){var d=Number(b[1]),c=Number(b[2]||1)-1,e=Number(b[3]||1)-1,f=Number(b[4]||0),h=Number(b[5]||0),j=Number(b[6]||0),k=Number(b[7]||0),l=!b[4]||
b[8]?0:Number(new g(1970,0)),m="-"===b[9]?1:-1,n=Number(b[10]||0),b=Number(b[11]||0);if(f<(0<h||0<j||0<k?24:25)&&60>h&&60>j&&1E3>k&&-1<c&&12>c&&24>n&&60>b&&-1<e&&e<D(d,c+1)-D(d,c))if(d=60*(24*(D(d,c)+e)+f+n*m),d=1E3*(60*(d+h+b*m)+j)+k+l,-864E13<=d&&864E13>=d)return d;return NaN}return g.parse.apply(this,arguments)};Date=q;Date.now||(Date.now=function(){return(new Date).getTime()});if("0".split(void 0,0).length){var R=String.prototype.split;String.prototype.split=function(a,b){return void 0===a&&0===
b?[]:R.apply(this,arguments)}}if("".substr&&"b"!=="0b".substr(-1)){var S=String.prototype.substr;String.prototype.substr=function(a,b){return S.call(this,0>a?0>(a=this.length+a)?0:a:a,b)}}m="\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff";if(!String.prototype.trim||m.trim()){m="["+m+"]";var T=RegExp("^"+m+m+"*"),U=RegExp(m+m+"*$");String.prototype.trim=function(){if(void 0===this||null===this)throw new TypeError("can't convert "+
this+" to object");return String(this).replace(T,"").replace(U,"")}}var s=function(a){if(null==a)throw new TypeError("can't convert "+a+" to object");return Object(a)}})();
